mysql:
    host: localhost
    user: root
    passwd: root
    db: jack_api_hacienda
email:
    host: smtp.gmail.com
    port: 587
    type: TLS
    user: cmonge@jackdevelopers.com
    password: Jack1351#
jwt_issuer: 'com.jackdevelopers.connexion'
jwt_secret: 'Hernan-API'
jwt_lifetime_seconds: 600
jwt_algorithm: 'HS256'
api_key: '61fe6e29-06ea-434b-bc2a-eae5b557eb45'